### ISSUE TITLE
[Question] Airdrop vs Gitlab

### ISSUE THREAD

**Issue by robsontenorio** [WilberGroup/airdrop#4]
Hi!

Once Gitlab has a built in cache mechanism for builded assets, this package will be useful in anyway for gitlab projects?

**Comment by aarondfrancis** [comment]
@robsontenorio I'm not sure how the Gitlab cache for bundled assets will work, so it's hard for me to say for sure... but it's possible to create different drivers for Airdrop, so a Gitlab driver could be created if it makes sense!

**Comment by AidasK** [comment]
yes it will, because you will be able to skip `npm run prod` and without this package you can't do it.

**Comment by aarondfrancis** [comment]
I just tagged a new release that include a GitHub Actions driver. I think it will probably work the same way as a Gitlab driver, but I've never used Gitlab. If there is a specific question in the future re: Gitlab, you can open another issue.

**Comment by AidasK** [comment]
I can confirm that @aarondfrancis implementation should work for gitlab too. We are already are using this package with gitlab, it's awesome

**Comment by aarondfrancis** [comment]
@AidasK nice! Do you have any more details you can share? I'd love to put it in the docs. Thanks!
