### ISSUE TITLE
Feature Request: Ignored files or patterns for triggers.

### ISSUE THREAD

**Issue by adrianspacely** [WilberGroup/airdrop#8]
I spotted a `.DS_Store` in my Airdrop debug output. Files like that are ignored by git, so the CI ended up with a different hash.

I was wondering if ignorable files or patterns could be supported for the triggers?

**Comment by aarondfrancis** [comment]
Mm yeah, that's annoying. 

So it doesn't do *patterns*, but it should support [excluding specific files](https://hammerstone.dev/airdrop/docs/main/triggers/file#including--excluding).

If I'm understanding correctly, that should get you there.  Does it, or did I misunderstand?

**Comment by adrianspacely** [comment]
The `.DS_Store` file pops up randomly in any folder on Macs, so you wouldn't know specifically where it would pop up. I just added a recursive find and delete to get around my issue.

Maybe another example is vim, you might want to exclude `*.swp` files from the trigger, but you wouldn't want to delete them as I did for `.DS_Store`.

**Comment by aarondfrancis** [comment]
This is a good point. I'll try to add it this week.

**Comment by aarondfrancis** [comment]
Done! https://github.com/hammerstonedev/airdrop/releases/tag/v0.2.1

Give it a go and let me know if that fixes it.

**Comment by adrianspacely** [comment]
Nice! Thanks for that 😁

It works. Also, for my Laravel Vapor build, I was removing *.txt files to reduce my asset count _(not sure why they generate)_. This feature cleaned up that part of my deploy script nicely!
